[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "minigrad"
version = "0.0.1"
authors = [
  { name="Vitor Petri", email="seu@email.com" },
]
description = "Um framework de diferenciação automática em Python"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["minigrad*"]
exclude = ["notebooks*", "tests*"]